- Reviewed by Toli Kuznets per ENG-236 - Fix for EG-422 - Updated CEPEsperProcessor to set the context classloader when invoking Esper API. It's only needed when setting the subscriber on the statement. However, the context class loader is also set when initializing esper runtime just to be safe. The context classloader is not set when sending events to esper intentionally as it sets the context classloader for all any module that receives data from esper which might have undesirable (or not well-understood) side-effects - Updated Strategy Agent to not depend on esper module anymore. After this change the cep system/esper modules will need to be copied to modules/jars sub-directory along with esper, antlr and cglib jars. Will work with Ken to make appropriate installer changes when checking these changes in. - Update StrategyAgent to catch Throwable instead as it has better behavior when bad things happen. like NoClassDefFoundError. - All unit tests pass. Module tested manually within strategy agent. - The installer will need to be updated to copy the cep jars and the dependencies to module/jars for things to be working again.
git-svn-id: https://source.marketcetera.org/root/trunk@10251 501a4a96-914b-0410-8454-f5988a4ca596